"$schema" = 'https://starship.rs/config-schema.json'


add_newline = false
format = "$time $username$hostname$directory$git_branch$git_status$direnv$cmd_duration$status> "


[time]
disabled = false
format = '[$time](white)'
time_format = '%I:%M:%S%P'

[username]
show_always = false
format = '[$user](white)@'

[hostname]
ssh_only = true
format = '[$hostname](bold #f5c2e7):'
trim_at = '.'

[directory]
format = "[$path]($style)"
style = "bold bright-white"
repo_root_style = "bold #cba6f7"
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 1

[git_branch]
format = "\\([$branch](bold #cba6f7)"
[git_status]
format = "[($conflicted$staged$modified$untracked$stashed)]($white)\\)"
conflicted = "[!](bold red)"
staged     = "+"
modified   = "*"
untracked  = "?"
stashed    = "âš‘"

[direnv]
disabled = false
format = ' [$allowed](bold #a6e3a1)'
allowed_msg = '@'
not_allowed_msg = 'ðŸ”’'

[status]
disabled = false
format = " \\[[$status]($style)\\]"

[cmd_duration]
min_time = 3_000 # 3sec
format = ' [$duration](bold #f9e2af)'
show_notifications = true
min_time_to_notify = 120_000 # 2min
notification_timeout = 2_000

# foltz@navi ~/c/dots (main) [1]> git remote -v
